[domains]
base = "example.com"
jellyfin = "jellyfin.example.com"
jellyseerr = "jellyseerr.example.com"
immich = "immich.example.com"
filebrowser = "filebrowser.example.com"
audiobookshelf = "audiobookshelf.example.com"
homepage-dashboard = "homepage-dashboard.example.com"
librespeedtest = "librespeedtest.example.com"
stirling-pdf = "stirling-pdf.example.com"
uptime-kuma = "uptime-kuma.example.com"
gotify = "gotify.example.com"
hedgedoc = "hedgedoc.example.com"
karakeep = "karakeep.example.com"
egg = "egg.example.com"
kanidm = "kanidm.example.com"
tailnet = "example-tailnet.ts.net"

[emails]
proton = "proton@example.com"
gmail = "gmail@example.com"

[misc]
kanidm_display_name = "Example Kanidm Display Name"
