creation_rules:
  - age: >-
      age1scvmf9n6ekrzrsqc3j69zm875jmhdnsqrdunexfqgl4k5awuqagsy0newt,
      age1l96tx5dlksn0klutsj26m9nt2chy78w5jvp83598n9xrlvpfsamqt0hawk,
      age1d9x7q8nnvk4h2je62ukynn8jvjd2x8nzzv8hx57rv20hpjrkaylq80mrse,
      age1wxfa9m4evtrwwvyxalagjyquuznmmdh2p0j4fqkvrpcq2emudycs90peck,
      age1cu4yscesep58ysvcv66e85xry7f99x6xjszyp00u3rwazj0rh9fqt0wwsl
stores:
  json:
    indent: 2
