# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable; # 580

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/88b8e672-d27c-4cf6-8aeb-5ed4895b429e";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  boot.initrd.luks.devices."luks-43c4b67b-f086-473d-ab86-c7ebea3d96e7".device =
    "/dev/disk/by-uuid/43c4b67b-f086-473d-ab86-c7ebea3d96e7";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F47A-3CBA";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # for the USB-A dock at work
  # TODO
  # broken, but fixed in 491981
  # boot.extraModulePackages = [ config.boot.kernelPackages.evdi ];
  # boot.initrd.kernelModules = [ "evdi" ];
  # services.xserver.videoDrivers = [ "displaylink" ];
  # environment.systemPackages = with pkgs; [ displaylink ];
  # systemd.services.dlm.wantedBy = [ "multi-user.target" ];
  # nixpkgs.overlays = [
  #   (self: super: {
  #     displaylink = super.displaylink.overrideAttrs {
  #       src = pkgs.fetchurl {
  #         name = "displaylink-620.zip";
  #         # downloading this implicitly agrees with their EULA
  #         url = "https://www.synaptics.com/sites/default/files/exe_files/2025-09/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu6.2-EXE.zip";
  #         hash = "sha256-JQO7eEz4pdoPkhcn9tIuy5R4KyfsCniuw6eXw/rLaYE=";
  #       };
  #     };
  #   })
  # ];

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
