labels:
  backend: local
  platform: linux/arm64
steps:
  - commands:
      - cd modules/private
      - echo $AGE_KEY_PRIVATE_DATA | nix shell nixpkgs#age --command age --decrypt -i - -o private.toml.decrypted private.toml
      - mv private.toml.decrypted private.toml
    environment:
      AGE_KEY_PRIVATE_DATA:
        from_secret: AGE_KEY_PRIVATE_DATA
    image: bash
    name: Decrypt Private Data
  - commands:
      - nix --show-trace --extra-experimental-features pipe-operators flake show
    image: bash
    name: Nix flake show
  - commands:
      - attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    image: bash
    name: Setup Attic
  - commands:
      - nix --show-trace --extra-experimental-features pipe-operators build --print-out-paths '.#nixosConfigurations.bell-avf.config.system.build.toplevel' -o 'result-bell-avf'
    image: bash
    name: Build bell-avf
  - commands:
      - nix --show-trace --extra-experimental-features pipe-operators path-info --closure-size -h $(readlink -f 'result-bell-avf')
    image: bash
    name: Show bell-avf info
  - commands:
      - attic push lounge-rocks:nix-cache 'result-bell-avf'
    image: bash
    name: Push bell-avf to Attic
  - commands:
      - nix --show-trace --extra-experimental-features pipe-operators build --print-out-paths '.#nixosConfigurations.pi3a.config.system.build.toplevel' -o 'result-pi3a'
    image: bash
    name: Build pi3a
  - commands:
      - nix --show-trace --extra-experimental-features pipe-operators path-info --closure-size -h $(readlink -f 'result-pi3a')
    image: bash
    name: Show pi3a info
  - commands:
      - attic push lounge-rocks:nix-cache 'result-pi3a'
    image: bash
    name: Push pi3a to Attic
  - commands:
      - nix --show-trace --extra-experimental-features pipe-operators build --print-out-paths '.#nixosConfigurations.pi4b.config.system.build.toplevel' -o 'result-pi4b'
    image: bash
    name: Build pi4b
  - commands:
      - nix --show-trace --extra-experimental-features pipe-operators path-info --closure-size -h $(readlink -f 'result-pi4b')
    image: bash
    name: Show pi4b info
  - commands:
      - attic push lounge-rocks:nix-cache 'result-pi4b'
    image: bash
    name: Push pi4b to Attic
