depends_on:
  - build-all-x86_64-linux
labels:
  backend: local
  platform: linux/amd64
runs_on:
  - failure
steps:
  - commands:
      - cd modules/private
      - echo $AGE_KEY_PRIVATE_DATA | nix shell nixpkgs#age --command age --decrypt -i - -o private.toml.decrypted private.toml
      - mv private.toml.decrypted private.toml
    environment:
      AGE_KEY_PRIVATE_DATA:
        from_secret: AGE_KEY_PRIVATE_DATA
    image: bash
    name: Decrypt Private Data
  - commands:
      - attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    image: bash
    name: Setup Attic
  - commands:
      - echo 'skipping'
    image: bash
    name: Build backus
  - commands:
      - echo 'skipping'
    image: bash
    name: Show backus info
when:
  branch:
    exclude:
      - no-private-data
    include:
      - '**'
  event:
    - push
  status:
    - failure
