depends_on:
  - build-all-x86_64-linux
  - build-leibniz
labels:
  backend: local
  platform: linux/amd64
runs_on:
  - success
  - failure
steps:
  - commands:
      - cd modules/private
      - echo $AGE_KEY_PRIVATE_DATA | nix shell nixpkgs#age --command age --decrypt -i - -o private.toml.decrypted private.toml
      - mv private.toml.decrypted private.toml
    environment:
      AGE_KEY_PRIVATE_DATA:
        from_secret: AGE_KEY_PRIVATE_DATA
    image: bash
    name: Decrypt Private Data
    when:
      status: failure
  - commands:
      - attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    image: bash
    name: Setup Attic
    when:
      status: failure
  - commands:
      - echo 'skipping'
    image: bash
    name: Build morse
    when:
      status: failure
  - commands:
      - echo 'skipping'
    image: bash
    name: Show morse info
    when:
      status: failure
when:
  branch:
    exclude:
      - no-private-data
    include:
      - '**'
  event:
    - push
