labels:
  backend: local
  platform: linux/amd64
steps:
  - commands:
      - nix --show-trace flake show
    image: bash
    name: Nix flake show
when:
  branch:
    exclude:
      - no-private-data
    include:
      - '**'
  event:
    - push
