labels:
  backend: local
  platform: linux/amd64
steps:
  - commands:
      - cd modules/private
      - echo $AGE_KEY_PRIVATE_DATA | nix shell nixpkgs#age --command age --decrypt -i - -o private.toml.decrypted private.toml
      - mv private.toml.decrypted private.toml
    environment:
      AGE_KEY_PRIVATE_DATA:
        from_secret: AGE_KEY_PRIVATE_DATA
    image: bash
    name: Decrypt Private Data
  - commands:
      - nix --show-trace flake show
    image: bash
    name: Nix flake show
  - commands:
      - nix --show-trace flake check --show-trace
    image: bash
    name: Nix flake check
  - commands:
      - attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    image: bash
    name: Setup Attic
  - commands:
      - nix --show-trace build --print-out-paths '.#nixosConfigurations.btr-wsl.config.system.build.toplevel' -o 'result-btr-wsl'
    image: bash
    name: Build btr-wsl
  - commands:
      - nix --show-trace path-info --closure-size -h $(readlink -f 'result-btr-wsl')
    image: bash
    name: Show btr-wsl info
  - commands:
      - attic push lounge-rocks:nix-cache 'result-btr-wsl'
    image: bash
    name: Push btr-wsl to Attic
  - commands:
      - nix --show-trace build --print-out-paths '.#nixosConfigurations.morse.config.system.build.toplevel' -o 'result-morse'
    image: bash
    name: Build morse
  - commands:
      - nix --show-trace path-info --closure-size -h $(readlink -f 'result-morse')
    image: bash
    name: Show morse info
  - commands:
      - attic push lounge-rocks:nix-cache 'result-morse'
    image: bash
    name: Push morse to Attic
  - commands:
      - nix --show-trace build --print-out-paths '.#nixosConfigurations.newton.config.system.build.toplevel' -o 'result-newton'
    image: bash
    name: Build newton
  - commands:
      - nix --show-trace path-info --closure-size -h $(readlink -f 'result-newton')
    image: bash
    name: Show newton info
  - commands:
      - attic push lounge-rocks:nix-cache 'result-newton'
    image: bash
    name: Push newton to Attic
  - commands:
      - nix --show-trace build --print-out-paths '.#nixosConfigurations.turing.config.system.build.toplevel' -o 'result-turing'
    image: bash
    name: Build turing
  - commands:
      - nix --show-trace path-info --closure-size -h $(readlink -f 'result-turing')
    image: bash
    name: Show turing info
  - commands:
      - attic push lounge-rocks:nix-cache 'result-turing'
    image: bash
    name: Push turing to Attic
